from odoo import models, fields, api, _, Command
from odoo.exceptions import UserError
from datetime import date

class SmartReorderPoWizard(models.TransientModel):
    _name = 'smart.reorder.po.wizard'
    _description = 'Generate Consolidated POs'

    def action_confirm_consolidation(self):
        active_ids = self.env.context.get('active_ids')
        if not active_ids:
            return {'type': 'ir.actions.act_window_close'}

        suggestions = self.env['smart.reorder.suggestion'].browse(active_ids)

        # Group and Construct
        grouped_suggestions = {}
        for rec in suggestions:
            config = rec._get_config(rec.company_id.id)
            if not config.allow_draft_po:
                raise UserError(_('Draft PO creation is disabled for company %s. Enable in Configuration → Company Settings.') % rec.company_id.name)
            if not rec.reorder_needed:
                continue
            
            vendor = rec.vendor_id or config.default_vendor_id
            if not vendor:
                raise UserError(_(
                    'No vendor for %s. Set a vendor on the product or configure a Default Vendor in settings.'
                ) % rec.product_id.display_name)
            
            key = (vendor.id, rec.company_id.id)
            grouped_suggestions.setdefault(key, self.env['smart.reorder.suggestion'])
            grouped_suggestions[key] |= rec

        if not grouped_suggestions:
            raise UserError(_('No suggestions requiring reordering were selected.'))

        created_pos = self.env['purchase.order']
        for (vendor_id, company_id), recs in grouped_suggestions.items():
            po_lines = []
            vendor = self.env['res.partner'].browse(vendor_id)
            for rec in recs:
                seller = rec.product_id._select_seller(partner_id=vendor, quantity=rec.suggested_reorder_qty)
                po_price = seller.price if seller else rec.product_cost

                po_lines.append(Command.create({
                    'product_id': rec.product_id.id,
                    'product_qty': rec.suggested_reorder_qty,
                    'price_unit': po_price,
                    'name': (
                        f'{rec.product_id.display_name} — Reorder Advisor '
                        f'{date.today()} (avg {rec.avg_monthly_demand:.1f}/month)'
                    ),
                }))
            
            po = self.env['purchase.order'].sudo().create({
                'partner_id': vendor_id,
                'company_id': company_id,
                'order_line': po_lines,
                'notes': (
                    f'Auto-generated by Smart Reorder Advisor (Consolidated)\n'
                    f'Analysis Date: {date.today()}'
                ),
            })
            created_pos |= po

            recs.sudo().write({
                'po_ids': [Command.link(po.id)],
                'reorder_needed': False,
            })

        if len(created_pos) == 1:
            return {
                'type': 'ir.actions.act_window',
                'name': 'Draft Purchase Order',
                'res_model': 'purchase.order',
                'res_id': created_pos.id,
                'view_mode': 'form',
                'target': 'current',
            }
        else:
            return {
                'type': 'ir.actions.act_window',
                'name': 'Draft Purchase Orders',
                'res_model': 'purchase.order',
                'domain': [('id', 'in', created_pos.ids)],
                'view_mode': 'list,form',
                'target': 'current',
            }
